### PR TITLE
Adds `mbstring` extension as package dependency

### LINKED ISSUE #6: PHP extension mbstring not listed as dependency in composer.json
I recently switched over to this package from the PhpSpec version.

When I tried to deploy [my application](https://xmldiff.herokuapp.com) to Heroku I encountered an error:

    Call to undefined function Phalcon\Diff\Renderer\Html\mb_strlen() on line 142 in php-diff/src/Diff/Renderer/Html/BaseArray.php

This is caused by the mbstring  extension not being registered as a dependency. The workaround for me was to add  the dependency in my propjects `composer.json.

```
    {
        "require" : {
            "ext-mbstring": "*"
        }
    }
```

As this is trivial to fix, I will send in a pull-request shortly.

### PR DESCRIPTION
**Pull request by Potherca**
Fixes #6.

### CODE REVIEW

**Comment by sergeyklay** [comment]
@Potherca 
We don't add changes directly to stable branches or `master`. Could you please send this PR to the `2.0.x` branch? So I can release patch asap

**Comment by Potherca** [comment]
I changed the target branch. Looks like two merge commits want to tag along. Is this okay?

(On a side note, it might be useful to add the PR/branch convention to the `CONTRIBUTING.md` to avoid future mixups).

**Comment by sergeyklay** [comment]
> add the PR/branch convention to the CONTRIBUTING.md

COuld you please send PR?
Thanks

**Comment by sergeyklay** [comment]
Thanks

**Pull request merged**
